Controllers/PasswordChangeController.cs
using KanbanMeeting.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KanbanMeeting.Controllers
{
    public class PasswordChangeController : Controller
    {
        // GET: PasswordChange
        KanbanEntities entity = new KanbanEntities();
        public ActionResult Index()
        {
            string personelId = Convert.ToString(Session["EmployeeId"]);

            if (personelId == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var personel = (from p in entity.mst_user where p.worker_code == personelId select p).FirstOrDefault();
            ViewBag.authorization_id = null;
            ViewBag.mesaj = null;
            ViewBag.sitil = null;

            return View(personel);
        }

        [HttpPost]
        public ActionResult Index(Guid id, string password, string newPassword, string newPasswordCheck)
        {
            var personel = (from p in entity.mst_user where p.id == id select p).FirstOrDefault();

            if (password != personel.password)
            {
                ModelState.AddModelError("password", "Eski parolanızı yanlış girdiniz.");
                return View(personel);
            }

            if (newPassword != newPasswordCheck)
            {
                ModelState.AddModelError("newPasswordCheck", "Yeni parola uyuşmuyor.");
                return View(personel);
            }

            personel.password = newPassword;
            personel.new_user_id = false;
            entity.SaveChanges();

            TempData["bilgi"] = personel.worker_name;
            ViewBag.mesaj = "Parolanız başarıyla değiştirildi.";
            ViewBag.sitil = "alert alert-success";
            ViewBag.yetkiTurId = personel.authorization_id;

            return RedirectToAction("Index");
        }
    }
}

Views/PasswordChange/Index.cshtml
@model KanbanMeeting.Models.mst_user
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/sweetAlert.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<!DOCTYPE html>
<title>Şifre Degiştirme</title>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Password Change</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/sign-in.css" rel="stylesheet" />
    <style>
        .form-signin {
            max-width: 400px;
            padding: 15px;
            background-color: #fff;
            border: 1px solid #ced4da;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            margin: 50px auto;
        }

        .form-floating {
            margin-bottom: 15px;
        }

        .btn-save {
            padding: 10px;
            background-color: #28a745;
            color: #fff;
            border: 1px solid #218838;
            border-radius: 5px;
            cursor: pointer;
        }

            .btn-save:hover {
                background-color: #218838;
            }
    </style>
</head>

<body>
    <br />
    <br />
    <br />
    <br />
    <div class="container">
        <div class="form-signin">
            @using (Html.BeginForm("Index", "PasswordChange", FormMethod.Post, new { @id = "myForm" }))
            {
                @Html.HiddenFor(m => m.id)
                <h1 class="h3 mb-2 fw-normal text-center">Password Change</h1>

                if (TempData["mesaj"] != null)
                {
                    <div class="alert @TempData["sitil"]">
                        @TempData["mesaj"]
                    </div>
                }
                else
                {
                    <div class="alert @ViewBag.sitil">
                        @ViewBag.mesaj
                    </div>
                }

                <div class="form-floating">
                    <input type="password" class="form-control" id="password" name="password" required>
                    <label for="password">Old Password</label>
                </div>

                <div class="form-floating">
                    <input type="password" class="form-control" id="newPassword" name="newPassword" required>
                    <label for="newPassword">New Password</label>
                </div>

                <div class="form-floating">
                    <input type="password" class="form-control" id="newPasswordCheck" name="newPasswordCheck" required>
                    <label for="newPasswordCheck">Confirm New Password</label>
                </div>

                <button class="btn btn-primary w-100 py-2" type="submit">Change Password</button>
            }
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>